{
  "estados": [
    "Ciudad de México",
    "Estado de México",
    "Morelos",
    "Querétaro",
    "Guerrero"
  ],
  "ciudades": {
    "Ciudad de México": [
      "Álvaro Obregón",
      "Azcapotzalco",
      "Benito Juárez",
      "Coyoacán",
      "Cuajimalpa de Morelos",
      "Cuauhtémoc",
      "Gustavo A. Madero",
      "Iztacalco",
      "Iztapalapa",
      "La Magdalena Contreras",
      "Miguel Hidalgo",
      "Milpa Alta",
      "Tláhuac",
      "Tlalpan",
      "Venustiano Carranza",
      "Xochimilco"
    ],
    "Estado de México": [
      "Atizapán de Zaragoza",
      "Coacalco de Berriozábal",
      "Cuautitlán Izcalli",
      "Huixquilucan",
      "Isidro Fabela",
      "Naucalpan de Juárez",
      "Nicolás Romero",
      "Ocoyoacac",
      "Tlalnepantla de Baz",
      "Tultepec",
      "Tultitlán",
      "Chalco",
      "Ixtapaluca",
      "La Paz",
      "Nezahualcóyotl",
      "Texcoco",
      "Tepetlaoxtoc",
      "Chicoloapan",
      "Chimalhuacán",
      "Valle de Chalco Solidaridad",
      "Tenango del Aire",
      "Temamatla",
      "Tlalmanalco",
      "Amecameca",
      "Ayapango",
      "Juchitepec",
      "Ozumba",
      "Tepetlixpa",
      "Xalatlaco",
      "Ocuilan",
      "Lerma"
    ],
    "Morelos": [
      "Amacuzac",
      "Atlatlahucan",
      "Axochiapan",
      "Ayala",
      "Coatetelco",
      "Coatlán del Río",
      "Cuautla",
      "Cuernavaca",
      "Emiliano Zapata",
      "Huitzilac",
      "Hueyapan",
      "Jantetelco",
      "Jiutepec",
      "Jojutla",
      "Jonacatepec de Leandro Valle",
      "Mazatepec",
      "Miacatlán",
      "Ocuituco",
      "Puente de Ixtla",
      "Temixco",
      "Tepalcingo",
      "Tepoztlán",
      "Tetecala",
      "Tetela del Volcán",
      "Tlalnepantla",
      "Tlaltizapán de Zapata",
      "Tlaquiltenango",
      "Tlayacapan",
      "Totolapan",
      "Xochitepec",
      "Xoxocotla",
      "Yautepec",
      "Yecapixtla",
      "Zacatepec",
      "Zacualpan de Amilpas",
      "Temoac"
    ],
    "Querétaro": [
      "Amealco de Bonfil",
      "Arroyo Seco",
      "Cadereyta de Montes",
      "Colón",
      "Corregidora",
      "El Marqués",
      "Ezequiel Montes",
      "Huimilpan",
      "Jalpan de Serra",
      "Landa de Matamoros",
      "Pedro Escobedo",
      "Peñamiller",
      "Pinal de Amoles",
      "Querétaro",
      "San Joaquín",
      "San Juan del Río",
      "Tequisquiapan",
      "Tolimán"
    ],
    "Guerrero": [
      "Acapulco de Juárez"
    ]
  }
}

